### ISSUE TITLE
fix your documenation

### ISSUE THREAD

**Issue by ds2k5** [albaintor/integration-orangetv#1]
### Description

I belive there is a typo in your: https://github.com/albaintor/integration-orangetv/blob/main/README.md

python3 intg-sonyavr/driver.py

change to

python3 intg-orangetv/driver.py

in the file: https://github.com/albaintor/integration-orangetv/blob/main/README.md

### How to Reproduce

see above

 

### Expected behavior

run as ...

### Integration version

0

### Additional context

.

**Comment by albaintor** [comment]
Thanks, this is fixed in https://github.com/albaintor/integration-orangetv/commit/31b6ae054ff54d0739f5a6dd778aa2b64b3d0893
